import { AdsReport, Note, Reminder, ActivityLog } from './types'

export const DUMMY_ADS_REPORTS: AdsReport[] = [
  {
    id: '1',
    store_id: '1',
    store: { id: '1', name: 'Realme Surabaya' },
    week_start: '2024-01-08',
    week_end: '2024-01-14',
    impressions: 125400,
    products_sold: 89,
    clicks: 3240,
    revenue: 45600000,
    ctr: 2.58,
    ad_spend: 3200000,
    orders: 89,
    roas: 14.25,
    best_roas_product_name: 'Realme C67 6/128GB',
    best_roas_value: 18.5,
    lowest_conversion_product_name: 'Realme Buds T300',
    lowest_conversion_cost: 12500,
    notes: 'Minggu ini performa iklan meningkat signifikan. Modal iklan dinaikkan dari Rp 400k menjadi Rp 500k/hari pada hari Rabu. Strategi diubah dari GMV Max Auto ke GMV Max ROAS untuk produk flagship. Kenaikan ROAS didorong oleh promo Realme Anniversary.',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-15T08:00:00Z',
    updated_at: '2024-01-15T08:00:00Z',
  },
  {
    id: '2',
    store_id: '1',
    store: { id: '1', name: 'Realme Surabaya' },
    week_start: '2024-01-15',
    week_end: '2024-01-21',
    impressions: 98700,
    products_sold: 72,
    clicks: 2850,
    revenue: 38400000,
    ctr: 2.89,
    ad_spend: 2800000,
    orders: 72,
    roas: 13.71,
    best_roas_product_name: 'Realme 12 Pro+ 5G',
    best_roas_value: 16.2,
    lowest_conversion_product_name: 'Realme GT Neo 5',
    lowest_conversion_cost: 18200,
    notes: 'Penurunan performa dibanding minggu lalu karena hari libur nasional. Strategi tetap GMV Max ROAS. Direkomendasikan naikkan budget Jumat-Minggu.',
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: '2024-01-22T09:00:00Z',
    updated_at: '2024-01-22T10:30:00Z',
  },
  {
    id: '3',
    store_id: '2',
    store: { id: '2', name: 'Holyfon' },
    week_start: '2024-01-08',
    week_end: '2024-01-14',
    impressions: 87600,
    products_sold: 54,
    clicks: 1980,
    revenue: 28900000,
    ctr: 2.26,
    ad_spend: 2100000,
    orders: 54,
    roas: 13.76,
    best_roas_product_name: 'iPhone 15 128GB',
    best_roas_value: 22.1,
    lowest_conversion_product_name: 'Samsung A14 5G',
    lowest_conversion_cost: 8900,
    notes: 'Holyfon fokus pada produk premium. iPhone 15 masih jadi produk terlaris.',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: '2024-01-15T11:00:00Z',
    updated_at: '2024-01-15T11:00:00Z',
  },
  {
    id: '4',
    store_id: '1',
    store: { id: '1', name: 'Realme Surabaya' },
    week_start: '2024-01-22',
    week_end: '2024-01-28',
    impressions: 142000,
    products_sold: 108,
    clicks: 4100,
    revenue: 62500000,
    ctr: 2.89,
    ad_spend: 4200000,
    orders: 108,
    roas: 14.88,
    best_roas_product_name: 'Realme C67 6/128GB',
    best_roas_value: 19.8,
    lowest_conversion_product_name: 'Realme Pad Mini',
    lowest_conversion_cost: 15600,
    notes: 'Performa terbaik bulan ini! Flash sale akhir bulan sangat membantu. Direkomendasikan pertahankan strategi GMV Max ROAS + tambah budget Flash Sale.',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-29T08:00:00Z',
    updated_at: '2024-01-29T08:00:00Z',
  },
  {
    id: '5',
    store_id: '3',
    store: { id: '3', name: 'Devilmimi' },
    week_start: '2024-01-08',
    week_end: '2024-01-14',
    impressions: 65400,
    products_sold: 41,
    clicks: 1540,
    revenue: 21800000,
    ctr: 2.35,
    ad_spend: 1800000,
    orders: 41,
    roas: 12.11,
    best_roas_product_name: 'Xiaomi Redmi Note 13',
    best_roas_value: 15.4,
    lowest_conversion_product_name: 'OPPO A78 5G',
    lowest_conversion_cost: 22000,
    notes: 'Performa stabil. Devilmimi fokus pada mid-range.',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-15T14:00:00Z',
    updated_at: '2024-01-15T14:00:00Z',
  },
]

export const DUMMY_NOTES: Note[] = [
  {
    id: '1',
    title: 'Evaluasi Strategi Iklan Q1 2024',
    type: 'Evaluasi Performa',
    datetime: '2024-01-20T10:00:00Z',
    tags: ['Iklan', 'Strategi', 'Q1'],
    participants: ['Fachrezy', 'Budi', 'Sari'],
    content: 'Diskusi mendalam mengenai efektivitas strategi iklan GMV Max Auto vs GMV Max ROAS. Hasil analisis menunjukkan bahwa GMV Max ROAS memberikan performa 23% lebih baik untuk produk Realme flagship.\n\nPoint penting:\n- Realme C67 konsisten ROAS >15x\n- Produk aksesoris perlu review budget\n- Flash sale weekend terbukti efektif',
    action_items: [
      { id: '1', text: 'Migrate semua toko ke GMV Max ROAS', completed: true },
      { id: '2', text: 'Buat laporan perbandingan bulanan', completed: false },
      { id: '3', text: 'Review budget iklan aksesoris', completed: false },
    ],
    additional_notes: 'Follow up meeting 2 minggu lagi untuk review implementasi.',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Review Performa Holyfon Januari',
    type: 'Review Mingguan',
    datetime: '2024-01-22T14:00:00Z',
    tags: ['Holyfon', 'Review', 'iPhone'],
    participants: ['Fachrezy', 'Rani'],
    content: 'Review performa toko Holyfon untuk bulan Januari. Fokus pada penjualan iPhone 15 yang menjadi produk unggulan.',
    action_items: [
      { id: '1', text: 'Tambah konten iklan iPhone 15 Pro', completed: false },
      { id: '2', text: 'Koordinasi dengan supplier untuk stok', completed: true },
    ],
    additional_notes: '',
    created_by: 'user-2',
    updated_by: 'user-2',
    created_at: '2024-01-22T14:00:00Z',
    updated_at: '2024-01-22T14:00:00Z',
  },
  {
    id: '3',
    title: 'Diskusi Produk Baru Realme 12 Series',
    type: 'Diskusi Produk',
    datetime: '2024-01-25T09:00:00Z',
    tags: ['Realme', 'Produk Baru', 'Launch'],
    participants: ['Fachrezy', 'Budi', 'Sari', 'Rani', 'Dani'],
    content: 'Pembahasan strategi launch produk Realme 12 Series yang akan masuk bulan Februari. Perlu persiapan iklan dan konten sejak dini.',
    action_items: [
      { id: '1', text: 'Siapkan materi iklan Realme 12 Pro+', completed: false },
      { id: '2', text: 'Brief desainer untuk banner iklan', completed: false },
      { id: '3', text: 'Koordinasi pre-order dengan supplier', completed: false },
    ],
    additional_notes: 'Target launch pertama di Realme Surabaya dan Holyfon.',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-25T09:00:00Z',
    updated_at: '2024-01-25T09:00:00Z',
  },
]

export const DUMMY_REMINDERS: Reminder[] = [
  {
    id: '1',
    title: 'Update Budget Iklan Mingguan',
    type: 'Update Iklan',
    datetime: '2024-01-29T08:00:00Z',
    tags: ['Budget', 'Rutin'],
    participants: ['Fachrezy'],
    content: 'Review dan update budget iklan semua toko untuk minggu baru. Pastikan sesuai performa minggu lalu.',
    action_items: [
      { id: '1', text: 'Review ROAS semua toko', completed: true },
      { id: '2', text: 'Adjust budget Realme Surabaya', completed: true },
      { id: '3', text: 'Adjust budget Holyfon', completed: false },
    ],
    additional_notes: '',
    status: 'pending',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-28T16:00:00Z',
    updated_at: '2024-01-28T16:00:00Z',
  },
  {
    id: '2',
    title: 'Deadline Laporan Bulanan Januari',
    type: 'Deadline Laporan',
    datetime: '2024-01-31T17:00:00Z',
    tags: ['Laporan', 'Deadline', 'Januari'],
    participants: ['Fachrezy', 'Budi'],
    content: 'Submit laporan performa iklan bulan Januari ke manajemen. Include semua 7 toko.',
    action_items: [
      { id: '1', text: 'Compile data semua toko', completed: false },
      { id: '2', text: 'Buat ringkasan eksekutif', completed: false },
      { id: '3', text: 'Kirim ke manager', completed: false },
    ],
    additional_notes: 'Format laporan: PDF + Excel',
    status: 'pending',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-25T10:00:00Z',
    updated_at: '2024-01-25T10:00:00Z',
  },
  {
    id: '3',
    title: 'Meeting Review Strategi February',
    type: 'Meeting',
    datetime: '2024-02-01T10:00:00Z',
    tags: ['Meeting', 'Strategi', 'Februari'],
    participants: ['Fachrezy', 'Budi', 'Sari', 'Rani'],
    content: 'Meeting bulanan untuk review strategi dan target Februari 2024.',
    action_items: [
      { id: '1', text: 'Siapkan deck presentasi', completed: true },
      { id: '2', text: 'Buat target per toko', completed: true },
      { id: '3', text: 'Review kompetitor', completed: false },
    ],
    additional_notes: 'Zoom meeting, link akan dikirim H-1',
    status: 'completed',
    created_by: 'user-2',
    updated_by: 'user-1',
    created_at: '2024-01-26T09:00:00Z',
    updated_at: '2024-02-01T12:00:00Z',
  },
  {
    id: '4',
    title: 'Flash Sale 2.2 Persiapan',
    type: 'Update Iklan',
    datetime: '2024-02-01T08:00:00Z',
    tags: ['Flash Sale', 'Shopee', '2.2'],
    participants: ['Fachrezy', 'Sari'],
    content: 'Persiapan iklan Flash Sale 2.2 Shopee. Semua toko harus ikut campaign ini.',
    action_items: [
      { id: '1', text: 'Daftarkan produk ke Flash Sale 2.2', completed: false },
      { id: '2', text: 'Naikkan budget 2x lipat H-1', completed: false },
      { id: '3', text: 'Setup voucher toko', completed: false },
    ],
    additional_notes: 'Target revenue 2x dari hari normal',
    status: 'pending',
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2024-01-27T11:00:00Z',
    updated_at: '2024-01-27T11:00:00Z',
  },
]

export const DUMMY_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: '1',
    table_name: 'ads_reports',
    record_id: '1',
    action: 'create',
    changed_by: 'user-1',
    timestamp: '2024-01-15T08:00:00Z',
    changes: {},
    user_name: 'Fachrezy',
  },
  {
    id: '2',
    table_name: 'ads_reports',
    record_id: '2',
    action: 'update',
    changed_by: 'user-2',
    timestamp: '2024-01-22T10:30:00Z',
    changes: { notes: 'Updated notes' },
    user_name: 'Budi',
  },
  {
    id: '3',
    table_name: 'notes',
    record_id: '1',
    action: 'create',
    changed_by: 'user-1',
    timestamp: '2024-01-20T10:00:00Z',
    changes: {},
    user_name: 'Fachrezy',
  },
]
